### List of New York State Counties ###
from enum import Enum

county_names = [
    "Albany",
    "Allegany",
    "Brooklyn",
    "Bronx",
    "Broome",
    "Cattaraugus",
    "Cayuga",
    "Chautauqua",
    "Chemung",
    "Chenango",
    "Clinton",
    "Columbia",
    "Cortland",
    "Delaware",
    "Dutchess",
    "Erie",
    "Essex",
    "Franklin",
    "Fulton",
    "Genesee",
    "Greene",
    "Hamilton",
    "Herkimer",
    "Jefferson",
    "Kings",
    "Lewis",
    "Livingston",
    "Madison",
    "Manhattan",
    "Monroe",
    "Montgomery",
    "Nassau",
    "New York",
    "Niagara",
    "Oneida",
    "Onondaga",
    "Ontario",
    "Orange",
    "Orleans",
    "Oswego",
    "Otsego",
    "Putnam",
    "Queens",
    "Rensselaer",
    "Richmond",
    "Rockland",
    "Saint Lawrence",
    "Saratoga",
    "Schenectady",
    "Schoharie",
    "Schuyler",
    "Seneca",
    "Staten Island",
    "Steuben",
    "Suffolk",
    "Sullivan",
    "Tioga",
    "Tompkins",
    "Ulster",
    "Warren",
    "Washington",
    "Wayne",
    "Westchester",
    "Wyoming",
    "Yates",
]

counties = [county.upper() for county in county_names]

CountyEnum = Enum("CountyEnum", counties)
